name: Test

permissions:
  checks: write
  pull-requests: write

on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python-version }}
    name: Execute on Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup-python-units
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run
        id: run
        run: |
          python tests/test.py natural.units
        continue-on-error: true
